/** Arabic text for the playground gallery, keyed by the English text. */
export const ar: Record<string, string> = {
  $0: '0 $',
  $12: '12 $',
  $199: '199 $',
  $29: '29 $',
  $299: '299 $',
  $399: '399 $',
  $99: '99 $',
  '+971 …': '+971 …',
  '1 project': 'مشروع واحد',
  '10:00 – 10:30': '10:00 – 10:30',
  '12 unread': '12 غير مقروءة',
  '2,342 reviews': '2,342 تقييمًا',
  '3–5 days, free': '3–5 أيام، مجانًا',
  '3–5 working days': '3–5 أيام عمل',
  'A new version is out.': 'صدر إصدار جديد.',
  'Accept the terms to continue.': 'وافق على الشروط للمتابعة.',
  Accordion: 'الأكورديون',
  'Account ID': 'رقم الحساب',
  Activity: 'النشاط',
  'Activity content.': 'محتوى النشاط.',
  'Add to cart': 'أضف إلى السلة',
  Alert: 'التنبيه',
  'Apps notifications': 'إشعارات التطبيقات',
  'As it appears on invoices.': 'كما يظهر في الفواتير.',
  Audio: 'الصوتيات',
  Available: 'متاح',
  'Avatar group': 'مجموعة الصور الرمزية',
  Badge: 'الشارة',
  Behance: 'Behance',
  Breadcrumb: 'مسار التنقل',
  'Building calm, accessible products': 'نبني منتجات هادئة وسهلة الوصول',
  Button: 'الزر',
  'Button variants and appearances': 'أنواع الأزرار ومظاهرها',
  'Can I return an item?': 'هل يمكنني إرجاع منتج؟',
  'Cancelled: Offsite': 'أُلغي: اجتماع خارجي',
  'Card declined': 'رُفضت البطاقة',
  'Card number': 'رقم البطاقة',
  Cart: 'السلة',
  'Changes save automatically.': 'تُحفظ التغييرات تلقائيًا.',
  'Changes saved.': 'حُفظت التغييرات.',
  Checkbox: 'مربع الاختيار',
  Checked: 'محدد',
  'Checkout example': 'مثال على الدفع',
  'Choose a country': 'اختر دولة',
  'Choose a plan': 'اختر خطة',
  'Choose a plan to continue.': 'اختر خطة للمتابعة.',
  'Choose a size.': 'اختر مقاسًا.',
  'Choose card': 'بطاقة الاختيار',
  'Clear filters': 'مسح عوامل التصفية',
  Code: 'البرمجة',
  'Collapsed (maxItems 3)': 'مطوي (3 عناصر كحد أقصى)',
  'Color palette': 'لوحة الألوان',
  Combobox: 'مربع الاختيار مع البحث',
  Company: 'الشركة',
  Costs: 'التكاليف',
  Country: 'الدولة',
  'Create an account': 'أنشئ حسابًا',
  Danger: 'خطر',
  'Data display': 'عرض البيانات',
  Default: 'افتراضي',
  Delete: 'حذف',
  Delivery: 'التوصيل',
  'Delivery speed': 'سرعة التوصيل',
  Design: 'التصميم',
  'Design System Designer': 'مصمم نظام التصميم',
  'Design review': 'مراجعة التصميم',
  'Design systems': 'أنظمة التصميم',
  Disabled: 'معطل',
  'Divided, with icons and meta': 'مقسمة، مع أيقونات وتفاصيل',
  Docs: 'المستندات',
  'Done: Standup': 'انتهى: الاجتماع اليومي',
  Dot: 'نقطة',
  'Down is good here': 'الانخفاض جيد هنا',
  Egypt: 'مصر',
  Email: 'البريد الإلكتروني',
  'Email me about': 'راسلني بخصوص',
  'Empty state': 'الحالة الفارغة',
  Enclosed: 'محاط',
  'Enclosed tabs example': 'مثال على علامات تبويب محاطة',
  'Enter all 16 digits.': 'أدخل الأرقام الستة عشر كلها.',
  'Error and disabled': 'خطأ ومعطل',
  Europe: 'أوروبا',
  'Example navigation': 'مثال على التنقل',
  'Example navigation with search': 'مثال على التنقل مع البحث',
  'Example side navigation': 'مثال على التنقل الجانبي',
  Export: 'تصدير',
  Express: 'سريع',
  Feedback: 'الملاحظات والحالات',
  Filled: 'ممتلئ',
  Footer: 'التذييل',
  'Form field': 'حقل النموذج',
  Forms: 'النماذج',
  Foundations: 'الأساسيات',
  Free: 'مجاني',
  'Free over $50.': 'مجاني للطلبات فوق 50 $.',
  'From a store': 'من أحد المتاجر',
  Full: 'كامل',
  'Full pagination example': 'مثال على ترقيم كامل',
  Ghost: 'شفاف',
  Google: 'Google',
  'Group of switches': 'مجموعة مفاتيح',
  'Group with overflow': 'مجموعة مع عدد إضافي',
  'Group, horizontal': 'مجموعة أفقية',
  'Head of Products': 'رئيسة المنتجات',
  Header: 'الترويسة',
  Headphones: 'سماعات الرأس',
  'Health and GPS': 'الصحة وتحديد الموقع',
  Help: 'المساعدة',
  Home: 'الرئيسية',
  Horizontal: 'أفقي',
  'Horizontal and error': 'أفقي مع خطأ',
  'How long does delivery take?': 'كم يستغرق التوصيل؟',
  'I accept the terms': 'أوافق على الشروط',
  'Icon end': 'أيقونة في النهاية',
  'Icon start': 'أيقونة في البداية',
  'Icons, messages and states': 'الأيقونات والرسائل والحالات',
  Inbox: 'البريد الوارد',
  Indeterminate: 'غير محدد',
  'Input field': 'حقل الإدخال',
  'Invite your team': 'ادعُ فريقك',
  'James Wilson': 'جيمس ويلسون',
  L: 'L',
  Large: 'كبير',
  'Large field': 'حقل كبير',
  Like: 'إعجاب',
  Line: 'خط',
  'Line tabs example': 'مثال على علامات تبويب بخط',
  LinkedIn: 'LinkedIn',
  List: 'القائمة',
  Locked: 'مقفل',
  M: 'M',
  'Maria Garcia': 'ماريا غارسيا',
  Medium: 'متوسط',
  'Medium field': 'حقل متوسط',
  'Meeting card': 'بطاقة الاجتماع',
  'Mentions and replies': 'الإشارات والردود',
  Message: 'الرسالة',
  Multiple: 'متعدد',
  'Multiple (chips)': 'متعدد (رقائق)',
  Navbar: 'شريط التنقل',
  Navigation: 'التنقل',
  'New orders': 'الطلبات الجديدة',
  'Next day, $12': 'اليوم التالي، 12 $',
  'Next working day': 'يوم العمل التالي',
  'No results': 'لا توجد نتائج',
  'Noise cancelling, 30-hour battery': 'عزل للضوضاء وبطارية 30 ساعة',
  Notes: 'ملاحظات',
  Notifications: 'الإشعارات',
  'Order example': 'مثال على طلب',
  Ordered: 'مرقمة',
  Orders: 'الطلبات',
  'Osama Eldrieny': 'أسامة الدريني',
  Outline: 'محدد الإطار',
  Overview: 'نظرة عامة',
  'Overview content.': 'محتوى النظرة العامة.',
  Pagination: 'ترقيم الصفحات',
  Paid: 'مدفوع',
  Patterns: 'الأنماط',
  Payment: 'الدفع',
  'Payment failed.': 'فشل الدفع.',
  Phone: 'الهاتف',
  'Pick up': 'استلام',
  Pill: 'كبسولة',
  'Pill tabs example': 'مثال على علامات تبويب كبسولية',
  Placed: 'تم الطلب',
  'Placeholder, error and disabled': 'نص إرشادي وخطأ ومعطل',
  Plan: 'الخطة',
  Portfolio: 'معرض الأعمال',
  Price: 'السعر',
  Pricing: 'الأسعار',
  Primary: 'أساسي',
  Privacy: 'الخصوصية',
  Pro: 'احترافي',
  'Product card': 'بطاقة المنتج',
  'Product design': 'تصميم المنتجات',
  Products: 'المنتجات',
  'Profile and security': 'الملف الشخصي والأمان',
  'Publish your first page': 'انشر صفحتك الأولى',
  'Radio group': 'مجموعة الخيارات',
  'Range with marks': 'نطاق مع علامات',
  Reason: 'السبب',
  'Refund rate': 'نسبة الاسترداد',
  Region: 'المنطقة',
  Reports: 'التقارير',
  'Required, optional and help': 'مطلوب واختياري ومساعدة',
  Research: 'البحث',
  Revenue: 'الإيرادات',
  S: 'S',
  Sales: 'المبيعات',
  'Sarah Chen': 'سارة تشين',
  Saving: 'جارٍ الحفظ',
  Search: 'بحث',
  'Search field': 'حقل البحث',
  'Search products': 'ابحث في المنتجات',
  Secondary: 'ثانوي',
  Select: 'القائمة المنسدلة',
  'Send me updates from': 'أرسل لي التحديثات من',
  'Sept 28': '28 سبتمبر',
  Settings: 'الإعدادات',
  'Settings content.': 'محتوى الإعدادات.',
  Shipped: 'تم الشحن',
  Shipping: 'الشحن',
  Shop: 'المتجر',
  'Side nav': 'التنقل الجانبي',
  'Sign in': 'تسجيل الدخول',
  Simple: 'بسيط',
  'Simple pagination example': 'مثال على ترقيم بسيط',
  Single: 'مفرد',
  'Single value': 'قيمة واحدة',
  Size: 'المقاس',
  Sizes: 'الأحجام',
  'Sizes and status': 'الأحجام والحالة',
  'Sizes, icons and states': 'الأحجام والأيقونات والحالات',
  Skill: 'المهارة',
  Skills: 'المهارات',
  Slider: 'شريط التمرير',
  Small: 'صغير',
  'Small and disabled': 'صغير ومعطل',
  'Small field': 'حقل صغير',
  'Smart Watch': 'ساعة ذكية',
  Solid: 'مصمت',
  Standard: 'عادي',
  'Starts in 5 min': 'يبدأ خلال 5 دقائق',
  Stat: 'الإحصائية',
  States: 'الحالات',
  Stepper: 'مؤشر الخطوات',
  Store: 'المتجر',
  Subtle: 'خفيف',
  Success: 'نجاح',
  Table: 'الجدول',
  Tabs: 'علامات التبويب',
  Team: 'الفريق',
  TechHub: 'تك هب',
  'Tell us why in a few words.': 'أخبرنا بالسبب في كلمات قليلة.',
  Terms: 'الشروط',
  Text: 'نصي',
  Textarea: 'مربع النص',
  Topics: 'المواضيع',
  Traffic: 'الزيارات',
  'Trial ends soon.': 'تنتهي الفترة التجريبية قريبًا.',
  'Try other words or clear the filters.': 'جرّب كلمات أخرى أو امسح عوامل التصفية.',
  'Two years on every product.': 'سنتان على كل منتج.',
  'Type a skill': 'اكتب مهارة',
  'UX writing': 'كتابة تجربة المستخدم',
  Unchecked: 'غير محدد',
  'United Arab Emirates': 'الإمارات العربية المتحدة',
  Unlimited: 'غير محدود',
  'Up is bad here': 'الارتفاع سيئ هنا',
  'User research': 'أبحاث المستخدمين',
  Username: 'اسم المستخدم',
  'Variants × appearances': 'الأنواع × المظاهر',
  Vertical: 'عمودي',
  'Vertical with an error': 'عمودي مع خطأ',
  'Vertical with descriptions': 'عمودي مع أوصاف',
  Visitors: 'الزوار',
  Volume: 'مستوى الصوت',
  Warning: 'تحذير',
  Warranty: 'الضمان',
  'We never share it.': 'لن نشاركه أبدًا.',
  'We reply within a day.': 'نرد خلال يوم.',
  Wearables: 'الأجهزة القابلة للارتداء',
  'Weekly summary': 'الملخص الأسبوعي',
  'Wireless Headphones Pro': 'سماعات لاسلكية احترافية',
  'With a keyboard shortcut': 'مع اختصار لوحة المفاتيح',
  'With actions': 'مع إجراءات',
  'With counter': 'مع عدّاد',
  'With roles': 'مع أدوار',
  'With search': 'مع بحث',
  Workspace: 'مساحة العمل',
  'X (Twitter)': 'X (تويتر)',
  'Yes, within 30 days.': 'نعم، خلال 30 يومًا.',
  'vs last month': 'مقارنة بالشهر الماضي',
  'you@example.com': 'you@example.com',
  '© 2026 TechHub': '© 2026 تك هب',
  'Theme playground': 'ساحة تجربة السمات',
  'Every component follows seven theme axes. Change them here; the preview, and the other prototypes, update.':
    'كل مكوّن يتبع سبعة محاور للسمة. غيّرها هنا، وستتحدث المعاينة والنماذج الأولية الأخرى.',
  Theme: 'السمة',
  Reset: 'إعادة تعيين',
  'Apply it in your app': 'طبّقها في تطبيقك',
  Brand: 'العلامة',
  Mode: 'الوضع',
  Language: 'اللغة',
  Typeface: 'الخط',
  Density: 'الكثافة',
  Radius: 'الزوايا',
  Shadow: 'الظل',
  Diamond: 'ماسي',
  Amber: 'كهرماني',
  Opal: 'أوبال',
  Light: 'فاتح',
  Dark: 'داكن',
  English: 'English',
  العربية: 'العربية',
  Sans: 'بدون زوائد',
  Serif: 'بزوائد',
  Comfortable: 'مريح',
  Compact: 'مضغوط',
  Square: 'مربعة',
  Round: 'مستديرة',
  Pills: 'كبسولية',
  Flat: 'مسطح',
  Raised: 'مرتفع',
  Date: 'التاريخ',
  Card: 'بطاقة',
  'Cash on delivery': 'الدفع عند الاستلام',
  'Apple Pay': 'Apple Pay',
};
