/**
 * Writes reports/contrast.md and, with --check, fails on contrast failures that are not
 * in reports/contrast-baseline.json (known failures awaiting a design decision).
 *
 *   node packages/tokens/tools/contrast-report.ts [--check] [--update-baseline]
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { checkContrast, resultKey, type PairResult } from './contrast.ts';
import { loadTokens, srcDir } from './resolve.ts';

const reportsDir = join(srcDir, '../reports');
const baselinePath = join(reportsDir, 'contrast-baseline.json');

const results = checkContrast(loadTokens());
const failures = results.filter((r) => !r.pass);
const baseline: string[] = existsSync(baselinePath)
  ? JSON.parse(readFileSync(baselinePath, 'utf8'))
  : [];

const row = (r: PairResult) =>
  `| ${r.theme} | \`${r.fg}\` | \`${r.bg}\` | ${r.fgValue} on ${r.bgValue} | ${r.ratio.toFixed(2)}:1 | ${r.required}:1 |`;
const table = (rows: PairResult[]) =>
  [
    '| Theme | Foreground | Background | Colors | Ratio | Needs |',
    '|---|---|---|---|---|---|',
    ...rows.map(row),
  ].join('\n');

const byTheme = [...new Set(results.map((r) => r.theme))]
  .map((theme) => {
    const all = results.filter((r) => r.theme === theme);
    const failed = all.filter((r) => !r.pass).length;
    return `| ${theme} | ${all.length} | ${all.length - failed} | ${failed} |`;
  })
  .join('\n');

const report = `# Contrast report

Generated by \`packages/tokens/tools/contrast-report.ts\`. Do not edit by hand.

WCAG 2.2 AA: text needs 4.5:1 (1.4.3), icons and focus indicators need 3:1 (1.4.11).
Each theme is checked with its brand and mode; other theme axes don't change colors.

## Summary

| Theme | Pairs | Pass | Fail |
|---|---|---|---|
${byTheme}

## Failures (${failures.length})

${failures.length ? table(failures.sort((a, b) => a.ratio - b.ratio)) : 'None.'}

## All pairs

${table(results)}
`;

mkdirSync(reportsDir, { recursive: true });
writeFileSync(join(reportsDir, 'contrast.md'), report);

if (process.argv.includes('--update-baseline')) {
  writeFileSync(baselinePath, JSON.stringify(failures.map(resultKey).sort(), null, 2) + '\n');
  console.log(`Baseline updated: ${failures.length} known failures.`);
}

const known = new Set(baseline);
const fresh = failures.filter((f) => !known.has(resultKey(f)));
const fixed = baseline.filter((k) => !failures.some((f) => resultKey(f) === k));
console.log(
  `Contrast: ${results.length} pairs, ${failures.length} failing (${failures.length - fresh.length} known), report in packages/tokens/reports/contrast.md`,
);
if (fixed.length) console.log(`Fixed since baseline (run --update-baseline): ${fixed.length}`);
if (process.argv.includes('--check') && fresh.length) {
  console.error(`New contrast failures:\n${fresh.map(resultKey).join('\n')}`);
  process.exitCode = 1;
}
